spring:
  main:
    banner-mode: off
  application:
    name: "flagmanager"

server:
  port: 8081

#keycloak:
#  public-client: true
#  auth-server-url: "http://127.0.0.1:8180/auth"
#  realm: "TodoApp"
#  resource: "todo-test-app"