spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    banner-mode: off
  datasource:
    url: "jdbc:h2:file:/Users/tomaszkrol/Documents/Development/flagmanager"
  application:
    name: "flagmanager"

server:
  port: 8081

#keycloak:
#  public-client: true
#  auth-server-url: "http://127.0.0.1:8180/auth"
#  realm: "TodoApp"
#  resource: "todo-test-app"